rabbitmq/rabbitmq-mqtt

- .gitignore
- include/rabbit_mqtt.hrl
- include/rabbit_mqtt_frame.hrl
- include/rabbit_mqtt_retained_msg_store.hrl
- src/rabbit_mqtt.erl
- src/rabbit_mqtt_processor.erl
- src/rabbit_mqtt_retained_msg_store.erl
- src/rabbit_mqtt_retained_msg_store_dets.erl
- src/rabbit_mqtt_retained_msg_store_ets.erl
- src/rabbit_mqtt_retainer.erl
- src/rabbit_mqtt_retainer_sup.erl
- src/rabbit_mqtt_sup.erl
- src/rabbit_mqtt_util.erl
- src/rabbit_mqtt_vhost_event_handler.erl
- src/rabbitmq_mqtt.app.src
- test/src/com/rabbitmq/mqtt/test/MqttTest.java
> Retained messages support

- src/rabbit_mqtt_processor.erl
> set auto_delete=false for QoS1 subscriptions

- src/rabbit_mqtt_processor.erl
- test/src/com/rabbitmq/mqtt/test/MqttTest.java
Fixes #37, reverts #30, adds more tests.
> Use auto-deleted queues for connections that set Clean Session

- src/rabbitmq_mqtt.app.src
- test/src/rabbitmq_mqtt_standalone.app.src
https://github.com/rabbitmq/rabbitmq-server/issues/453
> Remove unneeded TCP options from config in .app.src files

- src/rabbitmq_mqtt.app.src
- test/src/com/rabbitmq/mqtt/test/MqttTest.java
> Change default subscription TTL to 24 hours

- include/rabbit_mqtt.hrl
- src/rabbit_mqtt_processor.erl
- src/rabbit_mqtt_reader.erl
Needed for the new Web-MQTT plugin.
Part of https://github.com/rabbitmq/rabbitmq-mqtt/issues/33
> Make send method configurable and export useful functions

- src/rabbit_mqtt_sup.erl
- src/rabbitmq_mqtt.app.src
Part of https://github.com/rabbitmq/rabbitmq-server/issues/528
> Make number of Ranch acceptors configurable

- .gitignore
- include/rabbit_mqtt.hrl
- src/rabbit_mqtt_reader.erl
- test/src/rabbit_mqtt_reader_tests.erl
Fixes #65 
Tests make sure messages had been published after all.
> Defer last receive after blocking

- priv/schema/rabbitmq_mqtt.schema
Schema for https://github.com/rabbitmq/rabbitmq-server/issues/550.
> cuttlefish schema

- include/rabbit_mqtt_frame.hrl
- src/rabbit_mqtt_frame.erl
- src/rabbit_mqtt_processor.erl
Fixes #61 
Using queue existence to check if there is a session saved for client id.
> Set session present flag if client id queue is present

- test/Makefile
> Update Paho Java git repo location

- src/rabbitmq_mqtt.app.src
Related to https://github.com/rabbitmq/rabbitmq-server/pull/776
Part of https://github.com/rabbitmq/rabbitmq-server/issues/735
> Stub for broker_version_requirements

- priv/schema/rabbitmq_mqtt.schema
Part of https://github.com/rabbitmq/rabbitmq-server/pull/917 
https://github.com/rabbitmq/rabbitmq-server/issues/909
> Add tcp linger option to schema

- src/rabbit_mqtt_processor.erl
- test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
> Retain last will message

- src/rabbit_mqtt_processor.erl
- test/auth_SUITE.erl
- test/processor_SUITE.erl
> Introduce mqtt_default_vhosts global parameter

- src/rabbit_mqtt_processor.erl
- test/auth_SUITE.erl
- test/processor_SUITE.erl
> Provide a way to pick client connection vhost from a port

- src/rabbit_mqtt_reader.erl
- test/reader_SUITE.erl
> Skip stats notification without connection pid

- src/rabbit_mqtt_reader.erl
> Improve logging when parsing invalid frames

- src/rabbit_mqtt_processor.erl
- test/java_SUITE.erl
- test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
Part of rabbitmq/rabbitmq-server#1085
> Add topic authorisation for consumption

- Makefile
- rabbitmq-components.mk
- src/rabbit_mqtt_processor.erl
- src/rabbit_mqtt_reader.erl
- src/rabbit_mqtt_sup.erl
- test/proxy_protocol_SUITE.erl
Part of rabbitmq/rabbitmq-server#589
> Add support for proxy protocol

- priv/schema/rabbitmq_mqtt.schema
Part of rabbitmq/rabbitmq-server#589
> Add proxy protocol Cuttlefish mapping

- src/rabbit_mqtt_reader.erl
Part of https://github.com/rabbitmq/rabbitmq-management-agent/issues/45
> Default to 0 for stats calculation

- src/rabbit_mqtt_processor.erl
- test/java_SUITE.erl
- test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
References rabbitmq/rabbitmq-server#1229
> Add client_id as an topic authz expandable variable

- src/rabbit_mqtt_connection_info.erl
> Propagate client ID to authn with dedicated module

- src/rabbit_mqtt_retained_msg_store_noop.erl
> Provide a no-op implementation of MQTT retainer

- src/rabbit_mqtt_processor.erl
Closes #163 
The session flag must be calculated before the internal queue is declared, otherwise it'll always return `true`. A temp channel must be created for the passive declare, as if the queue is not present the channel will be closed - this wasn't being handled properly before (not that it could ever happen then!).
> Session flag must be calculated before declaring the queue

- Makefile
- include/rabbit_mqtt.hrl
- rabbitmq-components.mk
- src/rabbit_mqtt_connection_sup.erl
- src/rabbit_mqtt_processor.erl
- src/rabbit_mqtt_reader.erl
- src/rabbit_mqtt_sup.erl
This set of PRs is ready. Full set listed in https://github.com/rabbitmq/rabbitmq-common/pull/279
Please describe the big picture of your changes here to communicate to the
RabbitMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.
A pull request that doesn't explain **why** the change was made has a much
lower chance of being accepted.
If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your abilities.
As long as we can understand the intent, it's all good.
What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating …
> Use the built-in Ranch PROXY protocol support

- src/rabbit_mqtt_reader.erl
Please describe the big picture of your changes here to communicate to the
RabbitMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.
A pull request that doesn't explain **why** the change was made has a much
lower chance of being accepted.
If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your abilities.
As long as we can understand the intent, it's all good.
What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here …
> Use {active,once} instead of async_recv

- src/rabbit_mqtt_processor.erl
- test/processor_SUITE.erl
> Add client ID to connection metadata

- src/rabbit_mqtt_processor.erl
- src/rabbit_mqtt_reader.erl
...instead of letting connection processes terminate and
the runtime to log scary looking crash reports.
STOMP has been doing this without logging for a while:
* https://github.com/rabbitmq/rabbitmq-stomp/blame/v3.7.x/src/rabbit_stomp_reader.erl#L344
* https://github.com/rabbitmq/rabbitmq-stomp/blob/v3.7.x/src/rabbit_stomp_processor.erl#L1167
Note that otherwise connection error handling is not affected
by this change.
While at it, added more debug logging.
Per discussion with @lukebakken.
[Python script](https://gist.github.com/michaelklishin/c8b27b5be93a75e50a9774e4b20e0189) used to reproduce.
References rabbitmq/rabbitmq-server#1862.
[#163716036]
> Handle socket write failures and log in a sensible way

- src/rabbit_mqtt_processor.erl
Fixes #179
Uses undefined MQTT return code 255 to mean "duplicate auth attempt"
> Handle duplicate CONNECT frame

- src/mqtt_node.erl
- test/cluster_SUITE.erl
In the cluster_SUITE testsuite:
All even-numbered nodes will use the same code base when using a secondary Umbrella. Odd-numbered nodes might use an incompatible code base. When cluster-wide client ID tracking was introduced, it was not put behind a feature flag because there was no need for one. Here, we
don't have a way to ensure that all nodes participate in client ID tracking. However, those using the same code should. That's why we limit our RPC calls to those nodes.
That's also the reason why we use a 5-node cluster: with node 2 and 4 which might not participate, it leaves nodes 1, 3 and 5: thus 3 nodes, the minimum to use Ra in proper conditions.
References #91, #195.
> mqtt_node: Skip incompatible nodes when configuring Ra cluster

- test/rabbit_auth_backend_mqtt_mock.erl
References rabbitmq/rabbitmq-auth-backend-oauth2#28
> Add state_can_expire/0 to mock authn/authz backend

- src/rabbit_mqtt_retainer_sup.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/2012
> Use `rabbit_vhost:list_names/0'

- Makefile
- include/rabbit_mqtt.hrl
- priv/schema/rabbitmq_mqtt.schema
- src/rabbit_mqtt_processor.erl
- src/rabbit_mqtt_retainer.erl
- src/rabbit_mqtt_util.erl
- test/config_schema_SUITE_data/rabbitmq_mqtt.snippets
- test/java_SUITE.erl
- test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
- test/util_SUITE.erl
Fixes #206 
Details available in [this message](https://groups.google.com/d/msg/rabbitmq-users/1-IrGIcg03o/6YHiJvL3BQAJ)
> Add Sparkplug namespace translation support

- test/java_SUITE.erl
- test/java_SUITE_data/Makefile
- test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
Upgrading to the latest Eclipse paho library requires some fixes.
> Fix java test suite

- test/java_SUITE.erl
- test/java_SUITE_data/Makefile
- test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
- test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/rabbit-test.sh
The current test suite has some shared state between tests that has been problematic. This work will attempt to simplify the necessary topic permissions as well.
> Refactor java tests

- src/rabbit_mqtt_util.erl
Cache topic translation for performance optimisation
> cache topic translation results

- test/auth_SUITE.erl
Part of https://github.com/rabbitmq/rabbitmq-server/pull/2172.
> Make it possible to override client ID in some tests

- src/rabbit_mqtt_connection_sup.erl
- src/rabbit_mqtt_retainer_sup.erl
- src/rabbit_mqtt_sup.erl
Resolves issue reported here:
https://groups.google.com/g/rabbitmq-users/c/7CWSiZwgLJQ
Depends on rabbitmq/rabbitmq-server#2439
> Revert two commits for #233
