rabbitmq/rabbitmq-mqtt

include/rabbit_mqtt.hrl
src/rabbit_mqtt_processor.erl
src/rabbit_mqtt_vhost_event_handler.erl

On `master` we only check authorization indirectly, at the level of the AMQP objects created behind the scenes. This PR adds explicit authorization checks at the level of MQTT topics.
This is done by calling `rabbit_access_control:check_resource_access` using the new resource kind of `mqtt_topic`. This works fine with  the `internal` and `ldap` auth backends, though it is possible third-party auth backends only expects kinds `exchange` and `queue`. With that in mind, I am considering putting the new authorization checks behind a configuration flag which defaults to off. I'll wait for some feedback before doing so, though.

Check authorization at MQTT topic level

---

src/rabbit_mqtt_connection_sup.erl
src/rabbit_mqtt_reader.erl
src/rabbit_mqtt_sup.erl

Part of rabbitmq/rabbitmq-server#260.
Tests pass here. I had to go with gen_server2:enter_loop because of the ranch:accept_ack call. Regardless everything should behave the same as before, it's just an alternative way to start such a process.

Use Ranch for TCP acceptor pool

---

src/rabbit_mqtt_reader.erl

This function includes operations that must be performed by
processes owning sockets.
Part of https://github.com/rabbitmq/rabbitmq-server/issues/446

Use rabbit_net:accept_ack instead of ranch:accept_ack

---

src/rabbit_mqtt_processor.erl

Due to a match clause ordering issue it wasn't the case. A compiler warning correctly
suggested that something was wrong.
Fixes #41 along the way.
Will investigate if it can be backported to `stable`.

Make sure that authentication with username taken from TLS/x509 certificate succeeds

---

src/rabbit_mqtt_processor.erl
test/src/rabbit_mqtt_processor_tests.erl

Usually if the MQTT client gives a username with a colon, the part before the colon is used as the AMQP vhost. I happen to have an application that wants to use usernames which contain colons without them being interpreted specially; maybe someone else does too, so I thought I would add this option.

[WIP] add option to ignore colons in usernames

---

src/rabbit_mqtt_processor.erl
test/src/com/rabbitmq/mqtt/test/MqttTest.java

Fixes #21.
Replace QoS2 is treated as QoS1.
It's not quite correct, because [spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349278) mention that QoS2 messages sent to a QoS0 topic should not be duplicated, while QoS1 messages could be duplicated. 
But RabbitMQ should not duplicate `no_ack=true` messages anyway.

Downgrade QoS2 messages to QoS1

---

Makefile
src/rabbit_mqtt_reader.erl
test/src/rabbit_mqtt_reader_tests.erl

Fixes #62
It's just a quick fix, because as you can see in tests, publish sent after alarm and block are being processed (Still not blocked payload). Which means that blocking is not correct.

Handle resource alarms messages in MQTT reader

---

src/rabbit_mqtt_reader.erl

...of connection (flow control) state.
This makes it much easier to reason about flow control
state when looking at the management UI or monitoring tools
that poll HTTP API.
Now that rabbitmq/rabbitmq-management#41 is merged, there are
few arguments against always emitting stats.
Fixes #71.

Emit stats unconditionally

---

src/rabbit_mqtt_processor.erl

During the **amqp_connection:start** the method **check_user_login** is already executed, when it is called again it will call the user_login_authentication method again, it makes the authentication to be executed twice in a role. 
On most cases it will not be a problem, but when salted passwords are being used, it will be a problem.

Removing unnecessary check_user_login on process_login

---

src/rabbit_mqtt_connection_sup.erl
src/rabbit_mqtt_sup.erl

Part of rabbitmq/rabbitmq-server#541
Replace `MAX_WAIT` with `WORKER_WAIT` for workers and with `SUPERVISOR_WAIT` for supervisors.

Set bounded timeout for OTP workers

---

include/rabbit_mqtt_frame.hrl
src/rabbit_mqtt_retainer.erl
src/rabbit_mqtt_retainer_sup.erl

The old format is removed in Erlang 19.0, leading to build errors.
Also, get rid of the `use_specs` macro and thus always define `-spec()` & friends.
While here, unnify the style of `-type` and `-spec`.
References rabbitmq/rabbitmq-server#860.
[#118562897]
[#122335241]

Use the new -spec format

---

src/rabbit_mqtt_processor.erl
test/auth_SUITE.erl
test/java_SUITE.erl
test/java_SUITE_data/src/com/rabbitmq/mqtt/test/MqttTest.java
test/reader_SUITE.erl

Fixes #96 
The problem was that username and password fields had been checked separately and anonymous and SSL auth modes could interfere with this credentials. So a username without a password was treated like a SSL username and an anonymous password can be added to a non-anonymous username.
The new logic corresponds with the plugin documentation. If any credential (username or password) is provided, default credentials and SSL auth are ignored. If only one of the credentials is provided an error is reported.

Fixed authentication logic.

---

Makefile

Source dist tarballs made by `rabbitmq-server-release` doesn't include
testsuites, so `clean` target breaks under such conditions.
Complements https://github.com/rabbitmq/rabbitmq-server-release/pull/4

Fix `clean` make target for source dist tarballs

---

src/rabbit_mqtt_retainer_sup.erl
test/retainer_SUITE.erl

Fixes #86 
https://github.com/rabbitmq/rabbitmq-server/pull/1051 and https://github.com/rabbitmq/rabbitmq-common/pull/153 need to be merged first.

Support Erlang string vhosts in retainer supervisor

---

src/rabbit_mqtt_processor.erl
src/rabbit_mqtt_reader.erl
test/java_SUITE.erl
test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/rabbit-test.sh

check_resource_access used to be called with
the MQTT topic as resource name and kind = topic.
It makes more sense now to call check_topic_access
with the exchange as resource name, kind = topic,
and routing key in the context.
References rabbitmq/rabbitmq-server#505, closes #95 .

Use check_topic_access on publishing

---

src/rabbit_mqtt_retainer_sup.erl

Such conversion isn't safe but also isn't necessary: those
names aren't supposed to be human-readable.
Fixes #123.

Don't use UTF-8 when calculating retainer_sup child names

---

src/rabbit_mqtt_processor.erl
test/command_SUITE.erl
test/java_SUITE.erl
test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/rabbit-test.sh

The check is actually already done at the AMQP level, but this commit
adds an "upstream" check, a more specific warning message, and a test.
Fixes #114

Check topic access when sending last will

---

src/rabbit_mqtt_reader.erl

Ensures stats are not emitted until the connection is stablished.
A non-pid value crashes the stats gc.
Part of https://github.com/rabbitmq/rabbitmq-management-agent/issues/42

Do not emit stats if connection has not been stablished

---

src/rabbit_mqtt_reader.erl

Stop during initialisation will cause the gen_server to terminate
with `undefined` state, this should be ignored
Closes #134

Avoid emitting stats when state is undefined

---

src/rabbit_mqtt_collector.erl
src/rabbit_mqtt_processor.erl

It is still up to discussion if the log sink should be `connection` or `channel`.
Fixes #142

Log MQTT processor log messages with connection sink.

---

src/rabbit_mqtt_processor.erl

This gives a greater chance to the Last Will message to be delivered because it will implicitely block `rabbit_mqtt_reader` while the server-side AMQP channel processes the message.
Without this, `rabbit_mqtt_reader` asks the Last Will message to be sent asynchronously and immediately closes the AMQP connection. The server-side AMQP channel might thus try to query an already closed connection.
Fixes #146.
[#150162950]

rabbit_mqtt_process: Close channels after send_will()

---

src/rabbit_mqtt_processor.erl

Fixes #132 
The main gist of the issue is that the internal message id used in `proc_state` could be overwritten [here](https://github.com/rabbitmq/rabbitmq-mqtt/blob/stable/src/rabbit_mqtt_processor.erl#L226-L232) by an incoming message id from a `?SUBSCRIBE` message. This is an edge case where many subscribe messages are sent concurrently with `QoS 1` publishes in a slower environment. The publishes get ahead of the subscribe messages at first but then subscribes catch up and the issue manifests itself.

Ensure maximum message id value is used when saving to process state

---

README.md

The HTML link to rabbitmq-plugins in the README was broken (missing `a`), so I fixed it by replacing it with the correct Markdown markup, which the rest of the document uses.
None.

Replace broken link with correct Markdown

---

.gitignore
src/rabbit_mqtt_processor.erl

Support global parameter values that are maps (as well as proplists).
Part of #156, rabbitmq/rabbitmq-management#528.

Support global parameter values that are maps

---

Makefile
priv/schema/rabbitmq_mqtt.schema
src/rabbit_mqtt_sup.erl

Bumps number of TLS connection acceptors to 10 by default. See rabbitmq/rabbitmq-server#1729
for context.
Part of rabbitmq/rabbitmq-server#1729.
[#161136615]

Use 10 TLS connection acceptors by default

---

src/rabbit_mqtt_reader.erl

The function is already called before calling
process_received_bytes, there doesn't seem to
be a reason to call it again.
Please describe the big picture of your changes here to communicate to the
RabbitMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.
A pull request that doesn't explain **why** the change was made has a much
lower chance of being accepted.
If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your abilities.
As long as we can understand the intent, it's all good.
What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill …

Remove a duplicate control_throttle

---

src/rabbit_mqtt_processor.erl
src/rabbit_mqtt_retainer.erl
test/retainer_SUITE.erl

The message retainer for MQTT messages was using the raw topic instead of the translated topic (amqp2mqtt). This caused unexpected behavior when subscribing to topics that contained dots.  
Non-retained messages being delivered to clients currently have the topic translated to MQTT (slash). This PR improves upon that by: making sure that the topic_name returned for a retained message is in MQTT(slash) format and retains the topic in MQTT (slash) format. 
I also increased the timeout for the tests, my development machine (VM on NAS) was not able to complete the test in < 60 seconds.
Not sure if this would be considered a breaking change or a bug fix.

Fix translation issue with retained messages.

---

test/java_SUITE_data/mvnw
test/java_SUITE_data/mvnw.cmd
test/java_SUITE_data/pom.xml

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://www.apache.org/licenses/LICENSE-2.0 migrated to:  
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).
* http://www.rabbitmq.com migrated to:  
https://www.rabbitmq.com ([https](https://www.rabbitmq.com) result 200).
These URLs were intentionally ignored.
* http://maven.apache.org/POM/4.0.0
* http://maven.apache.org/xsd/maven-4.0.0.xsd
* http://www.w3.org/2001/XMLSchema-instance

URL Cleanup

---

src/rabbit_auth_backend_mqtt_mock.erl
test/auth_SUITE.erl

This commit adds a test to check the MQTT client is properly propagated
to the authentication and authorization backends.
References rabbitmq/rabbitmq-server#1767
Note this PR uses a mock authn/authz to record calls during the test. The file is added to the main source directory to make the broker start properly (test modules are not available in the broker startup).

Add test to check client id propagation

---

Makefile
include/mqtt_machine.hrl
include/rabbit_mqtt.hrl
include/rabbit_mqtt_frame.hrl
src/Elixir.RabbitMQ.CLI.Ctl.Commands.DecommissionMqttNodeCommand.erl
src/mqtt_machine.erl
src/mqtt_node.erl
src/rabbit_mqtt.erl
src/rabbit_mqtt_collector.erl
src/rabbit_mqtt_processor.erl
src/rabbit_mqtt_reader.erl
src/rabbit_mqtt_sup.erl
test/cluster_SUITE.erl
test/java_SUITE.erl
test/java_SUITE_data/Makefile
test/java_SUITE_data/pom.xml
test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
test/reader_SUITE.erl

Uses a ra cluster to keep the client id tracking information - in
the state of the ra machine.
If nodes are decommissioned from the RMQ cluster, the command
decommission_mqtt_node must be invoked first to disconnect the clients
on that node and remove the node from the ra cluster.
[#135330629]

Cluster-wide MQTT client id tracking

---

src/mqtt_node.erl
src/rabbit_mqtt_collector.erl
src/rabbit_mqtt_processor.erl
src/rabbit_mqtt_reader.erl

On plugin startup, client ID tracker node should try to rejoin the cluster for a period of time (currently 500 seconds, the value is not particularly scientific). This means that a cluster can lose the majority of nodes for a period of time and still recover when a majority rejoins.
Restarting the plugin will renew the attempts.
While investigating a failure introduced in the original version of this PR
I've noticed a few curious decisions in `process_frame/3`, so I refactored it a bit
and improved logging. 
I've paired wiith @kjnilsson on the Ra part of this PR.
Closes #200.

Client ID tracker node should try to rejoin the cluster for a period of time

---

src/Elixir.RabbitMQ.CLI.Ctl.Commands.ListMqttConnectionsCommand.erl
test/command_SUITE.erl

The way connections are listed already contains all the connections, so
there is no need to reach out to all cluster nodes and aggregate the
results, as it results in duplicate lines.
The command test now uses a cluster to make sure connections are listed
properly in a cluster.
[#167639960]
Fixes #202

Do not reach out to all nodes when listing connections

---

test/java_SUITE_data/pom.xml
test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java
test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/tls/MqttSSLTest.java

Migrate to JUnit 5, use TestInfo to create test-related MQTT
client ID when possible, remove Awaitility in favor of a in-house
utility and the use of lambdas, clean some code.

Modernize Java test suite

---

.travis.yml
src/rabbit_mqtt_processor.erl
test/java_SUITE_data/src/test/java/com/rabbitmq/mqtt/test/MqttTest.java

QoS 2 was not downgraded to QoS 1 correctly when Last Will messages were sent.
Closes #214.

Downgrade QoS 2 to QoS 1 when sending Last Will

---

src/rabbit_mqtt_processor.erl
src/rabbit_mqtt_reader.erl

Backport AMQP channel topic access caching (performance optimisation).

cache topic access

---

include/rabbit_mqtt.hrl
src/rabbit_mqtt_collector.erl
src/rabbit_mqtt_processor.erl
src/rabbit_mqtt_reader.erl
test/cluster_SUITE.erl

To avoid blocking when registering or unregistering a client id. This is
ok as informing the current connection holder of the client id is
already async. This should be more scalable and provide much better MQTT
connection setup latency.
Requires: https://github.com/rabbitmq/ra/pull/166

Make interactions with Ra async

---

src/mqtt_node.erl

5s is a value that has caused false positives in multiple places in the past.

Use a higher Ra operation timeout

---

src/mqtt_machine.erl
test/mqtt_machine_SUITE.erl

When a client performs repeated requests the state machine would crash
with a match exception.
Add unit test suite for mqtt_machine.

Fix mqtt_machine crash bug

---

src/rabbit_mqtt.erl
src/rabbit_mqtt_internal_event_handler.erl
src/rabbit_mqtt_reader.erl
src/rabbit_mqtt_sup.erl

This makes the refs predictable and easy to compute
from a listener record. Then suspending all listeners
becomes a lot simpler.
While at it, make protocol applications clean up
their listeners when they stop. This way tests
and other callers that have to stop the app
would not need to know anything about
its listeners.
Part of rabbitmq/rabbitmq-server#2321

Maintenance mode event support
